config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :invoices
  resources :services
  resources :products
  resources :clients

  root to: redirect("/invoices")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :client
  has_many :line_items, dependent: :destroy
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :invoice
  belongs_to :product, optional: true
  belongs_to :service, optional: true

  validate :must_be_product_or_service

  def must_be_product_or_service
    if product.blank? && service.blank?
      errors.add(:base, "A line item must be either a product or a service")
    elsif product.present? && service.present?
      errors.add(:base, "A line item can't be both a product and a service")
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  def index
    @clients = Client.all
  end

  # GET /clients/1
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: "Client was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params)
      redirect_to @client, notice: "Client was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: "Client was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def client_params
    params.require(:client).permit(:name, :email)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  after_action :save_line_items, except: [:index]

  def index
    @invoices = Invoice.all
  end

  def show
    @client = @invoice.client

    @line_items = (
      @invoice.line_items.joins(:product).where("products.price_cents != 0") +
      @invoice.line_items.joins(:service).where("services.price_cents != 0")
    ).group_by { |line_item| line_item.service.present? ? :service : :product }

    @total = @line_items.values.flatten.map { |line_item|
      [line_item.price_override_cents ||
        line_item&.product&.price_cents ||
        line_item&.service&.price_cents, line_item.quantity]
    }.sum { |(price_cents, quantity)|
      price_cents * quantity
    }
  end

  def new
    @invoice = Invoice.new
  end

  def edit
  end

  def create
    @invoice = Invoice.new(invoice_params)

    if @invoice.save
      redirect_to @invoice, notice: "Invoice was successfully created."
    else
      render :new
    end
  end

  def update
    if @invoice.update(invoice_params)
      redirect_to @invoice, notice: "Invoice was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @invoice.destroy
    redirect_to invoices_url, notice: "Invoice was successfully destroyed."
  end

  private

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  def save_line_items
    return if @invoice.blank?
    @invoice.line_items.each(&:save)
  end

  def invoice_params
    params.require(:invoice).permit(:client_id, :net_days, :note)
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  def create
    @line_item = LineItem.new(line_item_params)

    if @line_item.save
      redirect_to @line_item, notice: "Line item was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /line_items/1
  def update
    if @line_item.update(line_item_params)
      redirect_to @line_item, notice: "Line item was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /line_items/1
  def destroy
    @line_item.destroy
    redirect_to line_items_url, notice: "Line item was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def line_item_params
    params.require(:line_item).permit(:invoice_id, :product_id, :service_id, :price_override_cents, :quantity, :description)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: "Product was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: "Product was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: "Product was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def product_params
    params.require(:product).permit(:name, :price_cents)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  def index
    @services = Service.all
  end

  # GET /services/1
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service, notice: "Service was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /services/1
  def update
    if @service.update(service_params)
      redirect_to @service, notice: "Service was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /services/1
  def destroy
    @service.destroy
    redirect_to services_url, notice: "Service was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_service
    @service = Service.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def service_params
    params.require(:service).permit(:name, :price_cents)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def td_css
    "whitespace-nowrap px-3 py-4 text-sm text-gray-500"
  end

  def btn_css
    "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def to_money(cents)
    return "$0.00" if cents == 0
    "$#{cents.to_s.insert(-3, ".")}"
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-2xl mb-2">Clients</h1>

<div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg overflow-x-auto">
  <table class="min-w-full divide-y divide-gray-200">
    <thead class="bg-gray-200">
      <tr>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Email</th>
        <th colspan="3" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"></th>
      </tr>
    </thead>

    <tbody>
      <% @clients.each_with_index do |client, index| %>
        <%= tag.tr class: index.odd? ? "bg-white" : "bg-gray-50" do %>
          <td class="<%= td_css %>"><%= client.name %></td>
          <td class="<%= td_css %>"><%= client.email %></td>
          <td class="<%= td_css %>"><%= link_to 'Show', client %></td>
          <td class="<%= td_css %>"><%= link_to 'Edit', edit_client_path(client) %></td>
          <td class="<%= td_css %>"><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Client', new_client_path, role: "button", class: btn_css %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-2xl mb-2"> Invoices </h1>

<div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg overflow-x-auto">
  <table class="min-w-full divide-y divide-gray-200">
    <thead class="bg-gray-200">
      <tr>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Client</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Net days</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Note</th>
        <th colspan="3" ></th>
      </tr>
    </thead>

    <tbody>
      <% @invoices.each_with_index do |invoice, index| %>
        <%= tag.tr class: index.odd? ? "bg-white" : "bg-gray-50" do %>
          <td class="<%= td_css %>"><%= invoice.client.name %></td>
          <td class="<%= td_css %>"><%= invoice.net_days %></td>
          <td class="<%= td_css %>"><%= invoice.note %></td>
          <td class="<%= td_css %> underline"><%= link_to 'Show', invoice %></td>
          <td class="<%= td_css %> underline"><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
          <td class="<%= td_css %> underline"><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Invoice', new_invoice_path, role: "button", class: btn_css %>

app/views/layouts/_sidebar.html.erb
<!-- Off-canvas menu for mobile, show/hide based on off-canvas menu state. -->
<div class="fixed inset-0 flex z-40 md:hidden" role="dialog" aria-modal="true">
  <!--
Off-canvas menu overlay, show/hide based on off-canvas menu state.

Entering: "transition-opacity ease-linear duration-300"
From: "opacity-0"
To: "opacity-100"
Leaving: "transition-opacity ease-linear duration-300"
From: "opacity-100"
To: "opacity-0"
  -->
  <div class="fixed inset-0 bg-gray-600 bg-opacity-75 opacity-0" aria-hidden="true"></div>

  <!--
Off-canvas menu, show/hide based on off-canvas menu state.

Entering: "transition ease-in-out duration-300 transform"
From: "-translate-x-full"
To: "translate-x-0"
Leaving: "transition ease-in-out duration-300 transform"
From: "translate-x-0"
To: "-translate-x-full"
  -->
  <div class="relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-gray-800 -translate-x-full">
    <!--
 Close button, show/hide based on off-canvas menu state.

 Entering: "ease-in-out duration-300"
 From: "opacity-0"
 To: "opacity-100"
 Leaving: "ease-in-out duration-300"
 From: "opacity-100"
 To: "opacity-0"
    -->
    <div class="absolute top-0 right-0 -mr-12 pt-2 opacity-0">
      <button type="button" class="ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
        <span class="sr-only">Close sidebar</span>
        <!-- Heroicon name: outline/x -->
        <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>

    <div class="flex-shrink-0 flex items-center px-4 text-white">
      Accounts Receivable
    </div>
    <div class="mt-5 flex-1 h-0 overflow-y-auto">
      <nav class="px-2 space-y-1">
        <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
        <%= link_to clients_path, class: "bg-gray-900 text-white group flex items-center px-2 py-2 text-base font-medium rounded-md" do %>
          <!--
    Heroicon name: outline/home

    Current: "text-gray-300", Default: "text-gray-400 group-hover:text-gray-300"
          -->
          <svg class="text-gray-300 mr-4 flex-shrink-0 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
          </svg>
          Clients
        <% end %>

        <%= link_to products_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white group flex items-center px-2 py-2 text-base font-medium rounded-md" do %>
          <!-- Heroicon name: outline/users -->
          <svg class="text-gray-400 group-hover:text-gray-300 mr-4 flex-shrink-0 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
          </svg>
          Products
        <% end %>

        <%= link_to services_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white group flex items-center px-2 py-2 text-base font-medium rounded-md" do %>
          <!-- Heroicon name: outline/folder -->
          <svg class="text-gray-400 group-hover:text-gray-300 mr-4 flex-shrink-0 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
          </svg>
          Services
        <% end %>

        <%= link_to invoices_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white group flex items-center px-2 py-2 text-base font-medium rounded-md" do %>
          <!-- Heroicon name: outline/calendar -->
          <svg class="text-gray-400 group-hover:text-gray-300 mr-4 flex-shrink-0 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
          Invoices
        <% end %>

        <%= link_to line_items_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white group flex items-center px-2 py-2 text-base font-medium rounded-md" do %>
          <!-- Heroicon name: outline/inbox -->
          <svg class="text-gray-400 group-hover:text-gray-300 mr-4 flex-shrink-0 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
          </svg>
          Line Items
        <% end %>
      </nav>
    </div>
  </div>

  <div class="flex-shrink-0 w-14" aria-hidden="true">
  </div>
</div>

<!-- Static sidebar for desktop -->
<div class="hidden md:flex md:w-64 md:flex-col md:fixed md:inset-y-0">
  <!-- Sidebar component, swap this element with another sidebar if you like -->
  <div class="flex-1 flex flex-col min-h-0 bg-gray-800">
    <div class="flex items-center h-16 flex-shrink-0 px-4 text-white bg-gray-900">
      Accounts Receivable
    </div>
    <div class="flex-1 flex flex-col overflow-y-auto">
      <nav class="flex-1 px-2 py-4 space-y-1">
        <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
        <%= link_to clients_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white group flex items-center px-2 py-2 text-sm font-medium rounded-md" do %>
          <!--
    Heroicon name: outline/home

    Current: "text-gray-300", Default: "text-gray-400 group-hover:text-gray-300"
          -->
          <svg class="text-gray-300 mr-3 flex-shrink-0 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
          </svg>
          Clients
        <% end %>

        <%= link_to products_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white group flex items-center px-2 py-2 text-sm font-medium rounded-md" do %>
          <!-- Heroicon name: outline/users -->
          <svg class="text-gray-400 group-hover:text-gray-300 mr-3 flex-shrink-0 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
          </svg>
          Products
        <% end %>

        <%= link_to services_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white group flex items-center px-2 py-2 text-sm font-medium rounded-md" do %>
          <!-- Heroicon name: outline/folder -->
          <svg class="text-gray-400 group-hover:text-gray-300 mr-3 flex-shrink-0 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
          </svg>
          Services
        <% end %>

        <%= link_to invoices_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white group flex items-center px-2 py-2 text-sm font-medium rounded-md" do %>
          <!-- Heroicon name: outline/calendar -->
          <svg class="text-gray-400 group-hover:text-gray-300 mr-3 flex-shrink-0 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
          Invoices
        <% end %>

        <%= link_to line_items_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white group flex items-center px-2 py-2 text-sm font-medium rounded-md" do %>
          <!-- Heroicon name: outline/inbox -->
          <svg class="text-gray-400 group-hover:text-gray-300 mr-3 flex-shrink-0 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
          </svg>
          Line Items
        <% end %>
      </nav>
    </div>
  </div>
</div>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-2xl mb-2">Line Items</h1>

<div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg overflow-x-auto">
  <table class="min-w-full divide-y divide-gray-200">
    <thead class="bg-gray-200">
      <tr>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Invoice</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Product</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Service</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Price override cents</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Quantity</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Description</th>
        <th colspan="3" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"></th>
      </tr>
    </thead>

    <tbody>
      <% @line_items.each_with_index do |line_item, index| %>
        <%= tag.tr class: index.odd? ? "bg-white" : "bg-gray-50" do %>
          <td class="<%= td_css %>"><%= line_item.invoice.id %></td>
          <td class="<%= td_css %>"><%= line_item.product&.name %></td>
          <td class="<%= td_css %>"><%= line_item.service&.name %></td>
          <td class="<%= td_css %>"><%= line_item.price_override_cents %></td>
          <td class="<%= td_css %>"><%= line_item.quantity %></td>
          <td class="<%= td_css %>"><%= line_item.description %></td>
          <td class="<%= td_css %>"><%= link_to 'Show', line_item %></td>
          <td class="<%= td_css %>"><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
          <td class="<%= td_css %>"><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Line Item', new_line_item_path, role: "button", class: btn_css %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Invoice:</strong>
  <%= @line_item.invoice.id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product&.name %>
</p>

<p>
  <strong>Service:</strong>
  <%= @line_item.service&.name %>
</p>

<p>
  <strong>Price override cents:</strong>
  <%= @line_item.price_override_cents %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @line_item.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @line_item.description %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-2xl mb-2">Products</h1>

<div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg overflow-x-auto">
  <table class="min-w-full divide-y divide-gray-200">
    <thead class="bg-gray-200">
      <tr>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Price cents</th>
        <th colspan="3" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each_with_index do |product, index| %>
        <%= tag.tr class: index.odd? ? "bg-white" : "bg-gray-50" do %>
          <td class="<%= td_css %>"><%= product.name %></td>
          <td class="<%= td_css %>"><%= product.price_cents %></td>
          <td class="<%= td_css %>"><%= link_to 'Show', product %></td>
          <td class="<%= td_css %>"><%= link_to 'Edit', edit_product_path(product) %></td>
          <td class="<%= td_css %>"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Product', new_product_path, role: "button", class: btn_css %>